#!/bin/bash

#Colours section
cyan='\033[0;36m'
reset='\033[0m'

if [ -f ".ins_check" ]; then
  printf "${cyan}Setup script has run previously. To force execution, delete '.ins_check'.${reset}\n"
  exit 1
fi

printf "${cyan}This script requires root privillege. Run with sudo.\n"
printf "Please install Go, Rust and Python manually before running this script.\n${reset}"
sleep 5

curr_dir=$(pwd)

# Make intro look more aesthetical
mkdir .tmp
wget "https://raw.githubusercontent.com/ritikx01/figlet_fonts/main/Delta%20Corps%20Priest%201.flf" -O .tmp/dcp1.flf
mv .tmp/dcp1.flf /usr/share/figlet
apt install figlet lolcat cowsay

mkdir $HOME/Tools 2>/dev/null
# DNS validator
cowsay DNS Validator | lolcat
git clone https://github.com/vortexau/dnsvalidator.git $HOME/Tools/dnsvalidator 2>/dev/null
cd $HOME/Tools/dnsvalidator
python3 setup.py install > /dev/null 2>&1
cd $curr_dir
# MassDNS
cowsay MassDNS | lolcat
git clone https://github.com/blechschmidt/massdns.git $HOME/Tools/massdns 2>/dev/null
cd $HOME/Tools/massdns
make >/dev/null 2>&1
sudo cp bin/massdns /usr/local/bin
cd $curr_dir
# PureDNS
cowsay PureDNS | lolcat
go install github.com/d3mondev/puredns/v2@latest
# Subfinder
cowsay Subfinder | lolcat
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
# Amass
cowsay amass | lolcat
go install -v github.com/OWASP/Amass/v3/...@master
# httpx
cowsay httpx | lolcat
go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
# gospider
cowsay gospider | lolcat
GO111MODULE=on go get -u github.com/jaeles-project/gospider > /dev/null 2>&1
# NtHiM
cowsay "Now the host is mine" | lolcat
cargo install NtHiM >/dev/null 2>&1
# rustscan
wget https://github.com/RustScan/RustScan/releases/download/2.0.1/rustscan_2.0.1_amd64.deb
sudo dpkg -i rustscan_2.0.1_amd64.deb
rm rustscan_2.0.1_amd64.deb
# anew
go install -v github.com/tomnomnom/anew@latest
# tok
wget https://raw.githubusercontent.com/tomnomnom/hacks/master/tok/main.go
go mod init tok
go mod tidy
go build
mv tok $HOME/go/bin
rm main.go
# Nuclei
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
# Duplicut
git clone git clone https://github.com/nil0x42/duplicut $HOME/Tools/duplicut
cd $HOME/Tools/duplicut
make
mv duplicut /usr/local/bin

cd $curr_dir
rm -rf .tmp

#Installation check
touch .ins_check
printf "This file is generated by the script to check if the setup.sh is executed or not. Delete if you want to manually run installer" > .ins_check
